export const subExpertiseMaps: { [key: string]: string } = {
  // Development
  '프론트엔드': 'FE Developer',
  '백엔드': 'BE Developer',
  '풀스택': 'FS Developer',
  '웹': 'Web Developer',
  '모바일': 'Mobile Developer',
  '임베디드': 'ESW Developer',
  'AI/ML': 'AI/ML Engineer',
  '웹 퍼블리셔': 'Web Publisher',
  '게임': 'Game Developer',
  '그래픽': 'Graphics Developer',
  '빅데이터': 'Big Data Developer',

  // Infrastructure
  'DevOps 엔지니어': 'DevOps Engineer',
  '클라우드': 'Cloud Engineer',
  'SRE': 'SRE',
  '보안': 'Security Engineer',
  '데이터': 'Data Engineer',
  '인프라': 'Infra Engineer',
  '시스템 관리자': 'System Administrator',
  '네트워크': 'Network Engineer',
  'IT 운영': 'IT Ops Specialist',
  '플랫폼': 'Platform Engineer',

  // Design
  'UI/UX 디자이너': 'UI/UX Designer',
  '프로덕트 디자이너': 'Product Designer',
  '플랫폼 디자이너': 'Platform Designer',
  'UX 리서처': 'UX Researcher',
  'UX 라이팅': 'UX Writer',
  '인터랙션 디자이너': 'Interaction Designer',
  '브랜드 디자이너': 'Brand Designer',
  'BX 디자이너': 'BX Designer',
  '그래픽 디자이너': 'Graphic Designer',
  '모션 디자이너': 'Motion Designer',
  '콘텐츠 디자이너': 'Content Designer',
  '프롬포트 디자이너': 'Prompt Designer',

  // Business
  '서비스 기획자': 'Service Planner',
  'PM/PO': 'PM/PO',
  '전략 기획자': 'Strategic Planner',
  '사업 운영 매니저': 'BO Manager',
  '그로스 마케터': 'Growth Manager',
  '프로덕트 마케터': 'Product Marketer',
  '데이터 분석가': 'Data Analyst',
  'CX 매니저': 'CX Manager',
  'CS 매니저': 'CS Manager',
  'CSM': 'CSM',
  '커뮤니티 매니저': 'Community Manager',

  // Corporate
  '인사 담장자': 'HR Specialist',
  '채용 매니저': 'RM',
  '조직문화 매니저': 'OC Manager',
  '재무 담당자': 'Treasurer',
  '회계 담당자': 'Accountant',
  '법무 담당자': 'Legal Specialist',
  'PR 매니저': 'PR Manager',
  '오피스 매니저': 'Office Manager',
};
